In [2]:
import pandas as pd
import numpy as np
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

In [3]:
tickers = ['PG','AAPL']

sec_data = pd.DataFrame()

for t in tickers :
    sec_data[t] = wb.DataReader(t,'quandl','2007-1-1','2018-3-1')['AdjClose']

In [4]:
sec_data = sec_data.iloc[::-1]
sec_returns = np.log(sec_data / sec_data.shift(1))
sec_returns

                  PG      AAPL
Date
2007-01-03       NaN       NaN
2007-01-04 -0.007621  0.021953
2007-01-05 -0.008624 -0.007147
2007-01-08  0.002202  0.004926
2007-01-09 -0.002517  0.079800
2007-01-10  0.011901  0.046746
2007-01-11  0.006207 -0.012448
2007-01-12  0.005554 -0.012394
2007-01-16  0.000000  0.025873
2007-01-17  0.010255 -0.022391
2007-01-18  0.002750 -0.063928
2007-01-19  0.008357 -0.006420
2007-01-22 -0.005614 -0.019511
2007-01-23 -0.001218 -0.012639
2007-01-24 -0.001982  0.011601
2007-01-25 -0.009047 -0.005204
2007-01-26 -0.000925 -0.010138
2007-01-29  0.000308  0.006537
2007-01-30 -0.004480 -0.004548
2007-01-31  0.004326  0.002102
2007-02-01  0.007219 -0.011615
2007-02-02  0.000000  0.000118
2007-02-05 -0.002912 -0.009603
2007-02-06 -0.008633  0.002499
2007-02-07 -0.001705  0.023489
2007-02-08  0.001705  0.000348
2007-02-09 -0.002480 -0.034350
2007-02-12 -0.004199  0.019150
2007-02-13  0.008536 -0.002123
2007-02-14  0.002624  0.007059
...              ...       ...
2018-01-18 -0.011247  0.000893
2018-01-19  0.009821 -0.004473
2018-01-22  0.008964 -0.008215
2018-01-23 -0.031394  0.000226
2018-01-24 -0.008345 -0.016057
2018-01-25  0.000340 -0.018012
2018-01-26 -0.006929  0.002335
2018-01-29 -0.009966 -0.020916
2018-01-30  0.001036 -0.005912
2018-01-31 -0.007040  0.002751
2018-02-01 -0.005691  0.002088
2018-02-02 -0.018813 -0.045170
2018-02-05 -0.038599 -0.018122
2018-02-06  0.016153  0.034572
2018-02-07 -0.006577 -0.021640
2018-02-08 -0.019993 -0.026807
2018-02-09 -0.003747  0.004176
2018-02-12  0.017489  0.042306
2018-02-13  0.002088  0.009968
2018-02-14 -0.010112  0.018269
2018-02-15  0.021216  0.033027
2018-02-16  0.002303 -0.003242
2018-02-20 -0.015372 -0.003369
2018-02-21 -0.013616 -0.004549
2018-02-22  0.007450  0.008904
2018-02-23  0.002594  0.016976
2018-02-26  0.007131  0.019266
2018-02-27 -0.013443 -0.003246
2018-02-28 -0.025401 -0.001515
2018-03-01  0.002290 -0.017672

[2809 rows x 2 columns]

In [27]:
sec_returns['PG'].mean()

0.00018767102795901115

In [7]:
daily = sec_returns[['PG','AAPL']].mean()
daily

PG      0.000188
AAPL    0.000985
dtype: float64

In [34]:
annual = (((daily+1)**250)-1)*100
print(str(annual) + '%')

PG       4.803120
AAPL    27.915995
dtype: float64%

In [35]:
daily_std = sec_returns[['PG','AAPL']].std()
daily_std

PG      0.010931
AAPL    0.020057
dtype: float64

In [38]:
annual_std = sec_returns[['PG','AAPL']].std()*250**0.5
annual_std

PG      0.172832
AAPL    0.317125
dtype: float64